---
- name: Install vault package
  tags: vault
  yum: name=vault
       enablerepo=linuxhq-{{ linuxhq_pkg }}
       state=present
       update_cache=yes
  register: vault_yum

- block:
    - name: Configure vault
      template: src={{ item.src }}
                dest={{ item.dst }}
                owner=root
                group=root
                mode={{ item.mode }}
      notify: restart vault
      with_items:
        - { src: vault.hcl.j2, dst: /etc/vault/vault.hcl, mode: '0600' }
        - { src: vault.logrotate.j2, dst: /etc/logrotate.d/vault, mode: '0644' }
        - { src: vault.sysconfig.j2, dst: /etc/sysconfig/vault, mode: '0644' }
    - name: Enable and start the vault service
      service: name=vault
               enabled=yes
               state=started
  tags: vault
  when: vault_yum|success
