---
- name: Ensure that the vault package is installed
  tags: vault
  become: true
  yum:
    enablerepo: "linuxhq-{{ linuxhq_pkg }}"
    name: vault
    state: present
  register: vault_yum

- name: Attempting to overlay vault configuration
  tags: vault
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: restart vault
  with_items:
    - { src: vault.hcl.j2, dst: /etc/vault/vault.hcl, mode: '0600' }
    - { src: vault.logrotate.j2, dst: /etc/logrotate.d/vault, mode: '0644' }
    - { src: vault.sysconfig.j2, dst: /etc/sysconfig/vault, mode: '0644' }
  when: vault_yum is success

- name: Ensure that vault is started and enabled on boot
  tags: vault
  become: true
  service:
    enabled: yes
    name: vault
    state: started
  when: vault_yum is success
...
